### ISSUE TITLE
"Back to Site" not showing

### ISSUE THREAD

**Issue by pablobh** [Log1x/modern-login#7]
# Problem 
WP default login page has a link on the bottom that says: "← Back to Site Name" that is currently missing.

## Example

This is the default login page:
![Screen Shot 2021-03-23 at 2 01 46 PM](https://user-images.githubusercontent.com/23288307/112203527-a3aea900-8be0-11eb-9cfa-9a00a12f3014.png)

This is the login page while using this plugin:
![Screen Shot 2021-03-23 at 2 02 03 PM](https://user-images.githubusercontent.com/23288307/112203525-a3161280-8be0-11eb-82c5-9e028583502f.png)

After inspecting the code I found a few things:

```css
.login #login #backtoblog { 
    display: none;
}

.login #login a {
    /* color: #0073aa; */
    color: var(--login-brand,#0073aa);
}
```

So, the link is there but there are two situations:
1. It has display:none;
2. It is using the same color as the background, thus making it "invisible".

## Possible solution
1. Remove the display:none from the css.
2. Change the color for the link

## Additional info
This also happens with the privacy policy page link. Since it also uses the colors from `.login #login a`, this would also benefit from the fix described before.
